### ISSUE TITLE
Using this squid in a "Run a squid" quest

### ISSUE THREAD

**Issue by abernatskiy** [yat1ma30/subsquid-cryptopunks-migration#5]
Hello. We're going to use this squid one of the upcoming "Run a squid" quests. Do you mind if we credit you as the author in the README and give a link to your repo?

**Comment by yat1ma30** [comment]
Changed visibility.

**Comment by abernatskiy** [comment]
Thanks! And yeah, valid concern about abusing a public service when running many copies of this. I'll comment out the code you mention.
